### ISSUE TITLE
Ranked

### ISSUE THREAD

**Issue by ajotanc** [LionelBergen/MundoScript#6]
Hello, how are you? I use your api to see the ranked data, but I was looking these days and an empty array is returning, could you take a look?

Follow link demonstrating
https://prnt.sc/wjg11u

**Comment by LionelBergen** [comment]
@ajotanc 
A new season started, so that's why the array is empty.
Here's the URL the program calls:
https://br1.api.riotgames.com/lol/league/v4/entries/by-summoner/xMG_i_DDvd9JDtqFmBCCCz408-FAhF8Sx5DZGyfMXvHC?api_key=your_api_key_here
(Replace your_api_key_here with your API key to see the result)

**Comment by ajotanc** [comment]
Thakns, It worked!
